### ISSUE TITLE
One of the slowest packages in atom

### ISSUE THREAD

**Issue by ProLoser** [AsaAyers/js-hyperclick#24] opened 2016-04-29 23:35 UTC
I am seeing atom slow down to a crawl (especially startup times) and this is one of the slowest packages.

![image](https://cloud.githubusercontent.com/assets/67395/14932254/5e38d5f2-0e28-11e6-9d1c-5426e06abc2d.png)

**Comment by AsaAyers** [comment] 2016-04-29 23:58
Duplicate of #21

**Closed by AsaAyers** 2016-04-29 23:58 UTC
