### ISSUE TITLE
Can not hyperclick with new JS proposal features

### ISSUE THREAD

**Issue by vitexikora** [AsaAyers/js-hyperclick#101] opened 2018-10-22 10:32 UTC
Is it possible for js-hyperclick to utilize project-based babel installation? 
I finally found out what is breaking hyperclicking for me, its some new JS features, whose support is supplied by babel plugins.
For example: @babel/plugin-proposal-nullish-coalescing-operator
Anytime I use `?.` anywhere in a file, hyperclicking won't work in that file.
Standard .babelrc installation.

**Comment by AsaAyers** [comment] 2018-10-22 15:16
I'm going to close this as a duplicate of #99, because in both cases the solution is for me to upgrade `js-hyperclick` to use Babel 7.

**Closed by AsaAyers** 2018-10-22 15:16 UTC

**Comment by vitexikora** [comment] 2018-10-23 07:41
Ok, so I suppose it is going to be universal.
Really looking forward to this feature! 👍
